### ISSUE TITLE
Issue version 1.0.0

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-highlight#4]
To issue a version:
1. test in Chrome, Firefox, IE11, Safari (if possible)
2. Put 1.0.0 in bower.json and as first line in `juicy-highlight.html` (similarly to https://github.com/Juicy/juicy-redirect/blob/gh-pages/src/juicy-redirect.html)
3. Commit change in bower json as `git commit -m "1.0.0"`
4. Create a new tag `git tag -a "1.0.0" -m "1.0.0"`
5. Push to GitHub (`git push && git push --tags`)
6. Describe the release at https://github.com/Juicy/juicy-highlight/releases (for first release it can be simply "First release")

**Comment by tomalec** [comment]
Regarding 2., I suggest adding version in `version: x.y.z` format as in PuppetJs/PuppetJs so it could be easily bumped by grunt task like in here: https://github.com/PuppetJs/PuppetJs/blob/gh-pages/Gruntfile.js#L30
@warpech, @miyconst  WDYT?

**Comment by warpech** [comment]
So, what you mean is that `grunt-bump` will recognize such pattern and bump the number automatically when run `grunt bump` command?

**Comment by tomalec** [comment]
Exactly

**Comment by warpech** [comment]
Cool! Let's do that in future versions (and other repos as well)

**Comment by miyconst** [comment]
@warpech, @tomalec, x.y.z means that version number will be sorted "descending"?
1.0.0 became 0.0.1?

The value in PuppetJs/bower.json is 0.3.2
https://github.com/PuppetJs/PuppetJs/blob/gh-pages/bower.json

Does this mean:
2 - major release
3 - minor release
0 - tiny release

correct?

**Comment by tomalec** [comment]
No, version will not be sorted, we will use [semver](http://semver.org/), I just used same notion as in semver spec.
